// Generated by Grafana k6 Studio (1.11.0) on 2026-02-25T17:21:29.994Z

import { browser } from "k6/browser";

export const options = {
  scenarios: {
    default: {
      executor: "shared-iterations",
      options: { browser: { type: "chromium" } },
    },
  },
};

export default async function () {
  const page = await browser.newPage();

  await page.goto("https://souderbroder-loan-lab.lovable.app/");

  await page.locator("div:nth-of-type(2) > .flex").click();

  await page.getByRole("button", { name: "Nästa", exact: true }).click();

  await page
    .getByRole("textbox", { name: "Personnummer *", exact: true })
    .fill("202612092391");

  await page
    .getByRole("textbox", { name: "Förnamn *", exact: true })
    .fill("aaa");

  await page
    .getByRole("textbox", { name: "Efternamn *", exact: true })
    .fill("cccc");

  await page
    .getByRole("textbox", { name: "E-post *", exact: true })
    .fill("mail@.kiksj.se");

  await page
    .getByRole("textbox", { name: "Telefonnummer *", exact: true })
    .fill("07000763674");

  await page
    .getByRole("textbox", { name: "Adress *", exact: true })
    .fill("ksjkjdvägen");

  await page
    .getByRole("textbox", { name: "Postnummer *", exact: true })
    .fill("12345");

  await page.getByRole("textbox", { name: "Stad *", exact: true }).fill("city");

  await page.getByRole("button", { name: "Nästaä", exact: true }).click();

  await page.getByLabel("Månadsinkomst (SEK) *", { exact: true }).fill("20000");

  await page.locator("html").click();

  await page
    .getByRole("textbox", { name: "Arbetsgivare *", exact: true })
    .fill("ab ab");

  await page
    .getByRole("spinbutton", { name: "Sidoinkomst (SEK/månad)", exact: true })
    .fill("5");

  await page.getByRole("button", { name: "Nästa", exact: true }).click();

  await page
    .getByRole("spinbutton", { name: "Lånebelopp (SEK) *", exact: true })
    .fill("100000");

  await page.getByRole("button", { name: "Nästa", exact: true }).click();

  await page
    .getByRole("button", { name: "Skicka ansökan", exact: true })
    .click();

  await Promise.all([
    page.waitForNavigation(),
    page
      .getByRole("button", { name: "Tillbaka till startsidan", exact: true })
      .click(),
  ]);
}
